### ISSUE TITLE
Error when using get/'-g' option.

### ISSUE THREAD

**Issue by DinizBortolotto** [aadityabagga/asbt#2]
root@darkstar:~# head /etc/asbt/asbt.conf 
# Variables for asbt. See the man page for more info.
# Repository for slackbuilds

REPODIR="$HOME/sl/slackbuilds"
# REPODIR="$HOME/git/slackbuilds"
# Where the downloaded source packages are to be placed.
# Leave it blank for saving it in the same directory as the slackbuild.
# SRCDIR="$HOME/src"
## SRCDIR=""

asbt -G asbt
...
Saving to: '/root/sl/slackbuilds/system/asbt/1.7.1.tar.gz'

1.7.1.tar.gz                100%[==========================================>]  29.94K  --.-KB/s   in 0.1s   

Last-modified header missing -- time-stamps turned off.
2015-10-21 19:30:58 (202 KB/s) - '/root/sl/slackbuilds/system/asbt/1.7.1.tar.gz' saved [30658/30658]

Renaming 1.7.1.tar.gz
mv: cannot stat '/1.7.1.tar.gz': No such file or directory

root@darkstar:~# v sl/slackbuilds/system/asbt
total 24
lrwxrwxrwx 1 root root    18 Oct 21 19:30 1.7.1.tar.gz -> /asbt-1.7.1.tar.gz (RED/broken link) <<<<
-rw-r--r-- 1 1016 users  438 Dec 28  2014 README
-rw-r--r-- 1 1016 users  944 May  9 21:10 README.Slackware
-rwxr-xr-x 1 1016 users 2356 May 31 00:42 asbt.SlackBuild*
-rw-r--r-- 1 1016 users  296 May 31 00:42 asbt.info
-rw-r--r-- 1 1016 users  378 Feb 18  2014 doinst.sh
-rw-r--r-- 1 1016 users  892 Apr 26 04:09 slack-desc

**Comment by abchk1234** [comment]
Thx for the report.

I tried to fix it:
https://github.com/aadityabagga/asbt/commit/8091b2cece3d2c5f7149cdca950a7395aa52c72c

**Comment by abchk1234** [comment]
New version released with above fix.
https://github.com/aadityabagga/asbt/releases/tag/1.7.2
